import Header from './components/Header'
import Footer from './components/Footer'
import './globals.css'

export const metadata = {
  title: 'My Blog',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <body>
        <Header />
        <div className='app-body'>
          {children}
        </div>
        <Footer />

      </body>
    </html>
  )
}
